import { Copy, Download, Save } from "lucide-react";

export function OutputPanel({ items }: { items: string[] }) {
  return (
    <section className="rounded-lg border border-line border-t-accent border-t-4 bg-white shadow-panel">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-line p-4">
        <div>
          <h2 className="font-black text-navy">Structured Output Preview</h2>
          <p className="text-sm text-steel">Mock business deliverable generated by the selected AI employee.</p>
        </div>
        <div className="flex gap-2">
          {[Copy, Save, Download].map((Icon, i) => (
            <button key={i} className="grid h-9 w-9 place-items-center rounded-md border border-line bg-white text-navy" title={["Copy", "Save", "Download"][i]}>
              <Icon className="h-4 w-4" />
            </button>
          ))}
        </div>
      </div>
      <div className="space-y-3 p-5">
        {items.map((item) => {
          const [label, ...rest] = item.split(":");
          return (
            <div key={item} className="rounded-md bg-mist p-4">
              <div className="text-sm font-black text-navy">{label}</div>
              <p className="mt-1 text-sm leading-6 text-graphite">{rest.join(":").trim()}</p>
            </div>
          );
        })}
      </div>
    </section>
  );
}
